facebook/opaque-ke

.github/workflows/main.yml
src/opaque.rs
src/tests/serialization.rs

Successful run here:
https://github.com/huitseeker/opaque-ke/runs/767068151?check_suite_focus=true

Make CI run on PRs as well 

---

src/group.rs
src/opaque.rs
src/oprf.rs
src/tests/opaque_ke_test.rs
src/tests/serialization.rs

Ligthen fully qualified syntax and some uses of `GenericArray`
Please refer to individual commit messages.
This uncontroversial fragment is intended as a base branch for me to issue other PRs on top of.

Straightforward cleanups

---

Cargo.lock
Cargo.toml

Not. now using the same upcoming dalek versions (curve25519-dalek v 3)

Update all dependencies to the latest version

---

src/hash.rs
src/lib.rs

Make Hash module public

---

Cargo.lock
Cargo.toml
examples/simple_login.rs
src/lib.rs

This adds a simple login example via command-line interface and also fixes some extraneous doc lines in lib.rs

Adding simple login example and fixing some docs

---

benches/oprf.rs
src/lib.rs
src/map_to_curve.rs
src/opaque.rs
src/oprf.rs
src/tests/opaque_ke_test.rs

- Removing pepper parameter
- Adding Token struct used in VOPRF RFC
- Got rid of blinding_factor_raw parameter, added id_u and id_s to parameters for test vectors as well

Some changes in order to conform to VOPRF spec

---

Cargo.lock
Cargo.toml
src/errors.rs
src/group.rs
src/key_exchange/tripledh.rs
src/keypair.rs
src/lib.rs
src/opaque.rs
src/serialization/tests.rs
src/tests/opaque_ke_test.rs

- just derive it on Key and KeyPair for now.
Eliminates a complex derivation.

Start integrating the derivable SizedBytes

---

.github/workflows/main.yml
src/key_exchange/tripledh.rs
src/serialization/mod.rs
src/serialization/tests.rs

Add cross-compilation on 32-bits + fix the associated bugs

---

examples/simple_login.rs
src/opaque.rs

Fixing simple_login example

---

.github/workflows/main.yml
examples/simple_login.rs
scripts/simple_login.exp
src/opaque.rs

Followup to #86 : runs a test script on the `simple_login` example

Test examples

---

benches/oprf.rs
src/opaque.rs
src/oprf.rs
src/tests/opaque_ke_test.rs

Adds info1, info2, einfo2, info3, einfo3 to test vector generation

Adding info and einfo fields to test vectors

---

examples/simple_login.rs
src/lib.rs
src/opaque.rs
src/serialization/tests.rs
src/tests/opaque_ke_test.rs

Moving id_u and id_s from the client API to registration finish

---

src/keypair.rs

Closes #109 
@PaulGrandperrin, you should now be able to do something like:
```
let kp = X25519KeyPair::from_private_key_slice(&private_key_bytes)?;
```

Adding a from_private_key_slice on KeyPair

---

src/envelope.rs
src/key_exchange/traits.rs
src/key_exchange/tripledh.rs
src/keypair.rs
src/messages.rs
src/opaque.rs
src/serialization/tests.rs
src/tests/full_test.rs
src/tests/mod.rs
src/tests/opaque_test_vectors.rs

Aligns with the RFC generated test vectors, fixing a bunch of errors along the way

Aligning test vectors with RFC generated ones

---

examples/digital_locker.rs
examples/simple_login.rs
src/key_exchange/tripledh.rs
src/lib.rs
src/opaque.rs
src/tests/full_test.rs
src/tests/opaque_test_vectors.rs

This is to match up with the RFC terminology

Renaming shared secret to session key

---

src/messages.rs
src/opaque.rs
src/serialization/tests.rs

Making message type parameters set to CipherSuite

---

README.md

Adding reference to wasm package and link to examples in README

---

src/key_exchange/tripledh.rs

Ensuring mac operations are constant-time

---

src/lib.rs
src/messages.rs
src/opaque.rs
src/serialization/mod.rs

Adding documentation of slow-hash + other features

---

src/key_exchange/traits.rs
src/key_exchange/tripledh.rs
src/messages.rs
src/opaque.rs
src/serialization/tests.rs

Fixes public key checking for #152

Ensure that all public keys are being checked when deserialized

---

src/errors.rs
src/group.rs
src/keypair.rs
src/messages.rs
src/opaque.rs
src/oprf.rs
src/serialization/tests.rs
src/tests/full_test.rs

Adding identity element checks and ensuring non-zero scalar selection

---

src/errors.rs
src/oprf.rs

More missing common traits

---

.github/workflows/main.yml
src/messages.rs

(cherry picked from commit 6062bdb5cd993a3bccf2fea26f1f379b1cc37257)

Switch CI to using stable instead of nightly toolchain

---

Cargo.lock
Cargo.toml
src/errors.rs
src/group.rs
src/key_exchange/traits.rs
src/key_exchange/tripledh.rs
src/messages.rs
src/opaque.rs
src/serialization/tests.rs
src/tests/full_test.rs

(cherry picked from commit b4882f8810aab9ef931150ab7dd885e51ac7ed3c)

Adding reflected value check on client side

---

src/ciphersuite.rs
src/envelope.rs
src/group/expand.rs
src/group/mod.rs
src/group/p256.rs
src/group/ristretto.rs
src/lib.rs
src/opaque.rs
src/oprf.rs
src/tests/voprf_test_vectors.rs

As discussed in #213. I made a couple of improvements on the way.

Merge `GroupWithMapToCurve` into `Group`

---

examples/digital_locker.rs
examples/simple_login.rs
src/ciphersuite.rs
src/envelope.rs
src/group/mod.rs
src/group/x25519.rs
src/key_exchange/tripledh.rs
src/keypair.rs
src/lib.rs
src/messages.rs
src/opaque.rs
src/serialization/tests.rs
src/tests/full_test.rs
src/tests/opaque_test_vectors.rs

As discussed, replaces #220.
I also added an implementation for X25519 and a test.

Separate AKE from OPRF take 2

---

.github/workflows/main.yml
Cargo.toml
src/envelope.rs
src/errors.rs
src/group.rs
src/key_exchange/traits.rs
src/key_exchange/tripledh.rs
src/keypair.rs
src/lib.rs
src/map_to_curve.rs
src/messages.rs
src/opaque.rs
src/oprf.rs
src/serialization/mod.rs
src/serialization/tests.rs
src/slow_hash.rs
src/tests/full_test.rs
src/tests/mock_rng.rs
src/tests/opaque_test_vectors.rs
src/tests/voprf_test_vectors.rs

Adding no_std support for v1

---

Cargo.toml
src/group/x25519.rs
src/keypair.rs
src/lib.rs
src/opaque.rs
src/slow_hash.rs
src/tests/full_test.rs
src/tests/opaque_test_vectors.rs

As discussed. I also upgraded the argon2 dependency to 0.3 along the way.
Fixes #180.

Add `SlowHash` configuration

---

src/lib.rs

Adding warning about client enumeration attacks for v1

---

src/group/p256.rs

Fix `is_square` and `is_zero`

---

src/group/p256.rs
src/lib.rs

@Sc00bz I basically copied what crypto-bigint does, but I don't bother converting to bigger sizes and just compare the `u8`s.
Fixes #239.

Constant time `cmov`

---

src/tests/full_test.rs
src/tests/mock_rng.rs
src/tests/test_opaque_vectors.rs

Fix Clippy

---

.github/dependabot.yml
src/tests/full_test.rs
src/tests/mock_rng.rs
src/tests/test_opaque_vectors.rs

Somehow I forgot making a PR for this.
See https://github.com/novifinancial/voprf/pull/37.

Add Dependabot

---

.github/workflows/main.yml
Cargo.toml
src/key_exchange/group/curve25519.rs
src/key_exchange/group/mod.rs
src/lib.rs
src/tests/full_test.rs

Rename `X25519` to `Curve25519`

---

.github/workflows/main.yml
Cargo.toml
benches/opaque.rs
src/key_exchange/group/curve25519.rs
src/key_exchange/group/ristretto255.rs
src/lib.rs
src/tests/full_test.rs

Based on https://github.com/novifinancial/voprf/pull/86 and basically the same.
Again, CI might need to be expanded, happy to add any suggestions to both PRs.
~~CI will fail until https://github.com/novifinancial/opaque-ke/pull/298.~~

Update `curve25519-dalek` to 4.0.0-pre.5

---

.github/workflows/main.yml
Cargo.toml
README.md
examples/digital_locker.rs
examples/simple_login.rs
src/lib.rs

Replaces https://github.com/facebook/opaque-ke/pull/310.

Update `rustyline` to v0.11

---

CHANGELOG.md
Cargo.toml
README.md

Publishing v3.0.0-pre.3

---

.github/workflows/main.yml
.github/workflows/publish.yml
CHANGELOG.md
Cargo.toml
README.md

Updating workflow dependencies

---

src/serialization/tests.rs

Addresses the clippy errors that popped up on the most recent commit to main branch (https://github.com/facebook/opaque-ke/commit/47b37779d417ac1b171b2f531e2cabfe7874be18)

Fixing clippy errors

---

.github/workflows/main.yml
Cargo.toml
README.md
examples/digital_locker.rs
examples/simple_login.rs
src/key_exchange/tripledh.rs
src/lib.rs
src/opaque.rs
src/oprf.rs
src/serialization/mod.rs
src/serialization/tests.rs
src/tests/full_test.rs
src/tests/mock_rng.rs
src/tests/opaque_test_vectors.rs
src/tests/voprf_test_vectors.rs

- Re-exports the curve25519-dalek crate for v1
- Updates MSRV to 1.65
- Fixes various clippy errors

[v1] Re-export curve25519-dalek

---

src/key_exchange/sigma_i/message.rs

Add missing copyright header from #378.

Add missing copyright header

---

src/key_exchange/mod.rs
src/messages.rs
src/opaque.rs

Update to Clippy v1.89

---

examples/digital_locker.rs
examples/simple_login.rs
src/lib.rs

Re-exporting argon2 and generic_array

---

CHANGELOG.md
Cargo.toml
tests/migration.rs

Add migration guide to changelog
