facebook/opaque-ke

Cargo.lock, src/ciphersuite.rs, src/lib.rs, src/opaque.rs, src/slow_hash.rs, src/tests/opaque_ke_test.rs, src/tests/serialization.rs
In order to make the high-level API easier to use, I am adding the CipherSuite trait to allow the user to specify which primitives they want to across all of the ClientRegstration, ClientLogin, SeverRegistration, ServerLogin structs, rather than having to specify the primitives to each one individually.
=> Adding CipherSuite trait to handle bundling of underlying crypto primitives

Cargo.lock, Cargo.toml, src/group.rs, src/key_exchange.rs, src/opaque.rs, src/oprf.rs, src/rkr_encryption.rs, src/tests/serialization.rs
PR open upstream to eventually update the `Ristretto::hash_to_curve` op:
https://github.com/dalek-cryptography/curve25519-dalek/pull/327
=> Update digest & hash libraries to their latest versions

.github/workflows/main.yml, README.md, src/key_exchange.rs, src/keypair.rs, src/tests/opaque_ke_test.rs, src/tests/serialization.rs
This groups a few simpler & straightforward  changes originally designed withing the key exchange customization PR, which make sense in the larger context.
Please see the individual commit messages.
=> Backports from the Key Exchange customization PR

.github/workflows/main.yml
This helps if we run into a package with a cargo-audit advisory, the wrong license, or anything else deny would issue an error on.
Successful run at 
https://github.com/huitseeker/opaque-ke/actions/runs/150799735
=> add deny check to CI

Cargo.lock, Cargo.toml, benches/oprf.rs, src/group.rs, src/lib.rs, src/map_to_curve.rs, src/oprf.rs
Run with 
`cargo bench  --bench oprf --features "bench"`
```bash
Finished bench [optimized] target(s) in 0.05s
Running target/release/deps/oprf-d1e1cd5c178af8b8
generate_oprf1 with Ristretto                                                                            
time:   [55.702 us 55.978 us 56.403 us]
Found 10 outliers among 100 measurements (10.00%)
4 (4.00%) high mild
6 (6.00%) high severe
generate_oprf2 with Ristretto                                                                             
time:   [45.674 us 46.028 us 46.488 us]
Found 11 outliers among 100 measurements (11.00%)
4 (4.00%) high mild
7 (7.00%) high severe
generate_oprf3 with Ristretto                                                                            
time:   [63.676 us 63.968 us 64.366 us]
Found 9 …
```
=> Benchmarks for the OPRF

Cargo.toml
The bench in benches/oprf.rs requires a feature to have visibility over private members, and doesn't work without it.
`cargo check --all-targets` is the standard quick way to check code under build & test targets, but does not specify features.
This simply skips the `benches` when the `"bench"` feature it depends on is not activated.
=> Re-establish `cargo check --all-targets`

.github/workflows/main.yml, Cargo.toml, src/lib.rs
Allow building & testing with:
`cargo test --features "u32-backend" --no-default-features`
Successful run with the new CI at https://github.com/huitseeker/opaque-ke/actions/runs/178883098 (ad below)
=> Pass-through x,curve2559 backends

src/envelope.rs, src/opaque.rs, src/tests/opaque_ke_test.rs
Hmac computation wasn't accounting for the nonce -- this was a bug
Also renaming opaque_key to export_key
=> Fix omission of nonce in hmac computation for envelope

src/opaque.rs, src/tests/serialization.rs
This also fixes crashes in:
- RegisterFirstMessage,
- LoginFirstMessage,
- ClientRegistration,
- ClientLogin
I also think, retrospectively, that this demonstrates a need for a systematic approach to (de)serialization (which of course may or may not be generic-array-derive).
=> Proptests exercising `try_from` for most structures based on random data

.github/workflows/main.yml, benches/oprf.rs, src/oprf.rs
This should avoid letting our benchmarking code get stale.
https://github.com/huitseeker/opaque-ke/actions/runs/238346044 for a successful run of the new CI.
=> Fix benches + run their compilation in CI

src/ciphersuite.rs, src/elligator/mod.rs, src/group.rs, src/hash.rs, src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/map_to_curve.rs, src/opaque.rs, src/tests/opaque_ke_test.rs, src/tests/serialization.rs
This PR rationalizes some of our (complex) uses of generics and types:
- TripleDH converts back-and-forth to and from `GenericArray` both on storage (in the `KE[1-4](State|Message)` types) and on entering / exiting the KE (`(to|from)_bytes`). The later is justified, but the former is not and this PR corrects it.
- We transform the hidden panics from `foo.copy_from_slice(x)` where `foo` is a `[u8; N]` into explicit `TryInto` instances (followed by expect + a justification).
- `LoginSecondMessage` now uses the `CipherSuite` instance rather than 4 different types.
- the `KeyExchange` trait now uses a single `KeyFormat` parameter for its 3 functions (just like `Hash`) instead of 3 generic functions (for which having distinct instantiations would make no sense).
- `Hash` defined two parameters …
=> Simplifications and Normalizations

src/key_exchange/traits.rs, src/key_exchange/tripledh.rs
Our Key exchange data structures came with a nasty `Repr = Key` constraint that limited the Key formats to be represented with a `Vec<u8>`, and really did not need that constraint. 
This removes it.
=> Make KeyExchange generic in KeyFormat

src/ciphersuite.rs, src/opaque.rs, src/tests/opaque_ke_test.rs
This required purgin the usage of the low-level Key access, but now we
should be able to replace the Key type piecemeal, like a proper generic type.
=> Remove the last superfluous Repr = Key

src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/opaque.rs, src/tests/serialization.rs
We can directly require the HRTB on `for<'r> TryFrom<&'r [u8]>`.
Eliminates needless to_vec.
=> Fix use of `TryFrom<Vec<u8>>` in key_exchange

.github/workflows/publish.yml
This publishes commits to master matched with a GH release. Relies on a GHA token named crates_io.
=> Add publishing job

src/lib.rs, src/opaque.rs, src/tests/opaque_ke_test.rs
To be landed after #108 (since it is a dependency). This adds documentation for the result structs and all of the "advanced features", namely:
- usage of the shared secret
- export key
- checking server_s_pk
- custom identifiers
- plain_info and confidential_info in key exchange
Addresses #107 and #97
=> Adding documentation for advanced usage + optional parameters

src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/lib.rs, src/opaque.rs, src/serialization/tests.rs, src/tests/opaque_ke_test.rs
This PR enables encryption for the optional e_info fields that can be populated during login.
Also, since in https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/109, we are going to be removing some of the optional info fields to simplify the protocol, I went ahead and made the change here as well.
Closes #113
=> Adding encryption algorithm and removing unnecesssary info fields

examples/digital_locker.rs, examples/simple_login.rs
Closes #121 
In the future, this should be a compile-time error instead of a run-time error.
=> Fixing examples to use Sha512 with Ristretto instead of Sha256

src/ciphersuite.rs
=> Restricting ciphersuite group to match hash output

Cargo.lock, Cargo.toml, examples/digital_locker.rs, src/envelope.rs, src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/map_to_curve.rs, src/messages.rs, src/opaque.rs, src/serialization/mod.rs, src/serialization/tests.rs, src/tests/full_test.rs
- Removing use of NONCE_SIZE and using NonceLen type instead
- Fixing digital locker example
- Modularizing the serialization of various messages when used in AKE section
Closes #124 and #126
=> Addressing various TODOs and minor cleanups

src/key_exchange/tripledh.rs, src/map_to_curve.rs
This is preferred (especially in loops) as it's sometimes faster than reconstructing the hasher object.
See [function's docs](https://docs.rs/digest/0.9.0/digest/trait.Digest.html#tymethod.finalize_reset)
=> Reuse hashers by `hasher.finalize_reset()`

Cargo.lock, Cargo.toml, src/group.rs
Same goal as #103, but without adjusting any curve25519-dalek library dependencies.
This is because we can just rely on calling the internals of `Scalar::random` in the one place where it is used.
Closes #101 
cc: @PaulGrandperrin
=> Updating rand_core to 0.6 (without curve25519-dalek library change)

Cargo.lock, Cargo.toml, examples/digital_locker.rs, examples/simple_login.rs, src/ciphersuite.rs, src/envelope.rs, src/group.rs, src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/lib.rs, src/opaque.rs, src/oprf.rs, src/serialization/tests.rs, src/tests/full_test.rs, src/tests/mock_rng.rs
This will allow for applications to use the rand library paired with opaque-ke, since the top-level API requires rand parameters anyway, and will hopefully make it more convenient for a wrapper protocol to sync with opaque without worrying about rand version incompatibilities.
=> Exporting rand

examples/digital_locker.rs, examples/simple_login.rs, src/envelope.rs, src/lib.rs, src/messages.rs, src/opaque.rs, src/serialization/tests.rs, src/tests/full_test.rs, src/tests/opaque_test_vectors.rs
It is more convenient if all top-level functions use the same name for serialization/deserialization, rather than some of them supporting to_bytes / try_from.
Closes #135
=> Converting to_bytes and try_from to serialize() and deserialize()

.github/workflows/main.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/keypair.rs, src/tests/full_test.rs, src/tests/opaque_test_vectors.rs
Closes https://github.com/novifinancial/opaque-ke/issues/149
Also updates the github actions to check for compatibility against Rust v1.41.0
=> Updating to 0.5 and removing generic_bytes_derive dependency

Cargo.lock, Cargo.toml, src/keypair.rs
Currently the main key structure is not zeroized on drop. This diff adds this best practice functionality.
=> Zeroize keys on drop

.github/workflows/main.yml, Cargo.lock, Cargo.toml, src/envelope.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/messages.rs, src/opaque.rs, src/serialization/mod.rs, src/tests/full_test.rs
Provide a standard interface for serialization and deserialization using serde.
This makes it much easier to pass messages as part of protocols.
Fixes #166
=> Implement serde serialization and deserialization

src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/messages.rs, src/opaque.rs, src/oprf.rs
This makes it much easier to handle the messages as part of a framework (e.g. actix where in some cases move-only is not possible). Note that it was _technically_ possible so far using `serialize` and `deserialize`, but that's inefficient and ugly.
Note that just using `#[derive(Clone)]` is not possible for many of the types, since they are generic over `CS`, and deriving `Clone` would add the requirement that `CS` is `Clone`, which in turns would require `KeyExchange` to be `Clone`, which doesn't make sense (we never own an instance of it).
=> Implement Clone for every message type

src/envelope.rs, src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/messages.rs, src/opaque.rs, src/tests/full_test.rs, src/tests/opaque_test_vectors.rs
With this change, it's no longer possible to pass a public key where a private one is expected, and vice-versa.
I *might* have made the mistake when using this library :)
=> Enforce public vs private keys via types

.github/workflows/main.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/slow_hash.rs
I removed the `slow-hash` feature and replaced it with `scrypt` and `argon`. As per spec recommendation, I chose Argon2id, but I am no cryptographer and a different variant might be desirable when used in OPAQUE.
Fixes #179.
=> Argon2 implementation

Cargo.toml, src/envelope.rs, src/impls.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/lib.rs, src/messages.rs, src/opaque.rs, src/oprf.rs
This is an attempt to make sure that all exposed types implement `Clone`, `Debug`, `Deserialize` and `Serialize`. As a bonus I threw in `Eq`, `Hash` and `PartialEq` because it was no extra effort.
I skipped on implementing it on the `XxxResult` types because their public members are covered, which works great for our use-case, but adding them would be simple.
`Hash` might not be appropriate in a couple of places, I wouldn't know.
=> Implement common traits

src/opaque.rs
I realized this is more in line with the style then #192.
This enables to obtain the servers public key during registration.
=> Expose public key in ClientRegistrationFinishResult

src/envelope.rs, src/key_exchange/tripledh.rs, src/map_to_curve.rs, src/opaque.rs, src/oprf.rs, src/serialization/mod.rs, src/serialization/tests.rs, src/tests/full_test.rs, src/tests/voprf_test_vectors.rs
I2OSP (according to RFC8017) says that an error should be thrown if x >= 256^xLen, this adds the check.
=> Adding i2osp error checking condition

Cargo.toml, src/errors.rs, src/group.rs, src/messages.rs, src/opaque.rs, src/serialization/tests.rs, src/tests/full_test.rs
Check that the beta value from the server is not equal to the alpha value upon the second round from the client. Checked for both registration and login.
Introduces a dependency on `constant_time_eq` for the constant-time check.
Also adds tests to ensure that a `ReflectedValueError` is thrown when this case is detected.
=> Adding reflected value check on client side

.github/workflows/main.yml, Cargo.toml, README.md, src/errors.rs, src/lib.rs
We discussed 1.53 actually, but it seems no dependency needs it, I also noticed that we don't document MSRV anywhere. Do you want me to add documentation? Is 1.51 alright or should I bump it to the newest right now, which is 1.54 actually?
=> Increase MSRV to 1.51

.github/workflows/main.yml, Cargo.toml, src/envelope.rs, src/errors.rs, src/group/expand.rs, src/group/mod.rs, src/group/p256.rs, src/group/ristretto.rs, src/impls.rs, src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/lib.rs, src/messages.rs, src/opaque.rs, src/oprf.rs, src/serialization/mod.rs, src/serialization/tests.rs, src/slow_hash.rs, src/tests/full_test.rs, src/tests/mock_rng.rs, src/tests/opaque_test_vectors.rs, src/tests/voprf_test_vectors.rs
Alternative to #223.
As far as I can see, we only need `std` to implement `Error` and testing, otherwise it's completely out of the picture.
CI still needs to be adjusted.
=> `no_std` support

.github/workflows/main.yml, Cargo.toml, src/envelope.rs, src/errors.rs, src/group/expand.rs, src/group/p256.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/lib.rs, src/messages.rs, src/opaque.rs, src/serialization/tests.rs, src/slow_hash.rs, src/tests/full_test.rs, src/tests/opaque_test_vectors.rs
Apparently rust and cargo can't check for dependency support for `no_std`, one easy way to test it is to use the `thumbv6m-none-eabi` target, which I included now in CI.
This helped narrow down what dependencies were actually broken for `no_std` support.
generic-bytes had to be removed, because it doesn't have `no_std` support. This wasn't an issue per se, but some of it's functionality had to be replaced with custom functions, back-porting this to opaque-ke 1.0 would be a breaking change I have no clue exactly how to solve.
A common bug, see https://github.com/rust-lang/cargo/issues/4866, unified std features from a dev-dependency on normal builds, this was easily rectified by switching to the new feature resolver version.
The new resolver has an MSRV of 1.51, which works fine for this …
=> Fix `no_std` support

src/envelope.rs, src/errors.rs, src/group/expand.rs, src/group/mod.rs, src/group/p256.rs, src/group/ristretto.rs, src/group/x25519.rs, src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/lib.rs, src/messages.rs, src/opaque.rs, src/serialization/mod.rs, src/serialization/tests.rs, src/slow_hash.rs, src/tests/full_test.rs, src/tests/voprf_test_vectors.rs
Getting rid of `PakeError`, and leaving only `InternalError` and `ProtocolError`. Also removing a bunch of unused errors.
Closes #215
=> Simplifying error handling

src/envelope.rs
This PR fixes the following compile error by removing a trait that could not be derived.
```
error[E0184]: the trait `Copy` may not be implemented for this type; the type has a destructor
--> src/envelope.rs:68:17
|
68 | #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Zeroize)]
|                 ^^^^ Copy not allowed on types with destructors
|
= note: this error originates in the derive macro `Copy` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0184`.
error: could not compile `opaque-ke` due to previous error
```
Thank you for your hard work, I love the library.
=> Remove Copy trait implementation from InnerEnvelopeMode

src/group/p256.rs
Porting some improvements from VOPRF, I guess this is unnecessary in the long run when we include VOPRF as a dependency?
See novifinancial/voprf#18.
=> P256 improvements

.github/workflows/main.yml, Cargo.toml, src/envelope.rs, src/errors.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/messages.rs, src/opaque.rs, src/serialization/tests.rs, src/tests/full_test.rs, src/tests/opaque_test_vectors.rs
Mirrors the changes from https://github.com/novifinancial/opaque-ke/pull/229/commits/c7e897b6a613450cde5667bf3a7984e7afa3625a for v1 branch
=> Adding support for thumbv6m-none-eabi

.github/workflows/main.yml
Installing taplo-cli started failing recently, see: https://github.com/tamasfe/taplo/issues/242
=> Addressing taplo-cli install issue

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Closes #262 and #260, ready for release 2.0.0-pre.2.
=> Adding documentation on RegistrationUpload and removing patch voprf in Cargo.toml

src/ksf.rs
This pull request changes the `Ksf` implementation for Argon2 and sets the salt length to 16 bytes (instead of the minimal length of 8 bytes), the value recommended for password hashing in section 3.1 of the Argon2 specification.
This also serves to improve interoperability: for example, with this change, it's possible to use `opaque-ke` in conjunction with `libopaque`, since it also uses a 16-byte salt by default.
Note that this will make existing registrations (i.e., those made with an 8-byte salt) invalid, since KSF parameters (including salt length) must stay the same across registration and login.
=> Change argon2 salt length to recommended value (16 bytes)

src/lib.rs
This is a passive warning to the server implementor to not blindly trust the client to send the same identifier in both `RegistrationRequest` and `RegistrationUpload`.
=> Document responsibility for server-side id. #276

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Fixes #279 and prepares for a v2.0.0-pre.3 release by updating some documentation
=> Fixing voprf dependency pinning

.github/workflows/main.yml, Cargo.toml, src/key_exchange/tripledh.rs, src/oprf.rs, src/serialization/mod.rs, src/serialization/tests.rs, src/tests/full_test.rs, src/tests/mock_rng.rs, src/tests/opaque_test_vectors.rs, src/tests/voprf_test_vectors.rs
This would allow compatibility between this older version and the newer ecosystem.
Alternatively, we could just specify "^1.1" to make sure it's _at least_ 1.1.
=> Upgrade zeroize to 1.5

.github/workflows/main.yml, Cargo.toml, README.md, benches/opaque.rs, examples/digital_locker.rs, examples/simple_login.rs, src/key_exchange/group/curve25519.rs, src/key_exchange/group/ristretto255.rs, src/lib.rs, src/tests/parser.rs
Depends on https://github.com/facebook/voprf/pull/90 and https://github.com/facebook/voprf/pull/102.
The upgrade to Rust 1.60 also necessitated some Clippy fixes.
=> Bump `voprf` to v0.5.0-pre.2

Cargo.toml, src/envelope.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/lib.rs, src/messages.rs, src/opaque.rs
Analogous to https://github.com/facebook/voprf/pull/100.
Requires https://github.com/facebook/opaque-ke/pull/304.
> Since we are now using Rust 1.60, we can use explicit crate features.
Rust-Analyzer had some serious issues with that `extern crate serde_ as serde`.
This also removes all implicit features, which is an improvement for users.
=> Only use explicit crate features

.github/workflows/main.yml, Cargo.toml, README.md, src/ksf.rs, src/lib.rs
Updates `argon2` to v0.5.
Doesn't really include any interesting changes for us except we now don't have to specify our own default salt length, because it's provided by `argon2` now.
See the [CHANGELOG](https://github.com/RustCrypto/password-hashes/blob/argon2-v0.5.0/argon2/CHANGELOG.md#050-2023-03-04).
=> Update `argon2` to v0.5

.github/workflows/main.yml, CHANGELOG.md, Cargo.toml, README.md
Also, bump to 0.6.2 for release.
I'm trying to publish a crate that depends on opaque 0.6 and (indirectly) on zeroize 1.5.7. The 0.6.1 of opaque_ke is still on zeroize ~1.1, so it's not compatible.
For me to release my crate, I'd need a 0.6.2 release.
(note that I _know_ that 0.6 is deprecated, but my crate will depend on _both_ opaque 0.6 and 3.0+ and will allow users to do a smooth transitions without having to reset their passwords)
=> Fix zeroize dependency in a more future-proof fashion

Cargo.toml
Bumps `voprf` to v0.5.0-pre.4 and `curve25519-dalek` to v4.0.0-rc.2.
Replaces #320.
=> Bump `voprf` to v0.5.0-pre.4

Cargo.toml, src/key_exchange/group/curve25519.rs
The `Scalar` type isn't compatible with X25519 anymore, so instead we use a plain `[u8; 32]`.
Requires https://github.com/facebook/voprf/pull/113.
=> Bump `curve25519-dalek` to v4.0.0-rc.3

src/lib.rs
Maybe I missed something and it's due some configuration, but so far we have only seen 64 byte `export_key` and `session_key`.
=> update docs: clarify export_key and session_key length

src/lib.rs, src/opaque.rs
Addresses https://github.com/facebook/opaque-ke/issues/343
=> Clarifying the persisting of server setup

src/ciphersuite.rs, src/hash.rs, src/key_exchange/group/mod.rs, src/keypair.rs, src/lib.rs, src/opaque.rs, src/tests/opaque_vectors.rs
From https://github.com/facebook/opaque-ke/pull/344#discussion_r1346656152.
=> Add `clippy::doc_markdown`

.github/workflows/main.yml, Cargo.toml, README.md, src/errors.rs, src/key_exchange/tripledh.rs, src/lib.rs, src/opaque.rs, src/serialization/mod.rs, src/tests/full_test.rs, src/tests/test_opaque_vectors.rs
This primarily fixes recent clippy issues and also updates the voprf dependency. Also bumps MSRV to 1.74.
Addresses #359
=> Updating voprf dependency

src/lib.rs
This tweaks the documentation on the main module, in order to add some details on the outcome of the client login final step. In particular, it clarifies the result of `ClientLogin::finish()` both on success and on errors and it adds some intra-crate links to the relevant structures and fields.
=> docs: add details for client login final step

.github/workflows/main.yml, Cargo.toml, deny.toml, src/ciphersuite.rs, src/envelope.rs, src/errors.rs, src/key_exchange/group/curve25519.rs, src/key_exchange/group/elliptic_curve.rs, src/key_exchange/group/mod.rs, src/key_exchange/group/ristretto255.rs, src/key_exchange/traits.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/lib.rs, src/messages.rs, src/opaque.rs, src/serialization/tests.rs, src/tests/full_test.rs, src/tests/mod.rs, src/tests/remote_key.rs
I apologize in advance to squash so many unrelated changes into a single commit and PR!
Let me know if you want me to split this up into multiple commits or PRs and I'm happy to put in the work!
---
The `SecretKey` trait has one big limitation: it doesn't support async operations. This became especially important with the advent of [cloud HSMs](https://aws.amazon.com/kms), where operations can even happen over the Internet between different services.
The intuitive solution would have been to introduce another trait: `SecretKeyAsync`, or just add another method to `SecretKey` and users can just slap `unimplemented!()` in the synchronous method. We can still do this with actually some minor changes, but I instead opted for a different solution: removing the `SecretKey` trait entirely. …
=> Rework `SecretKey` API to facilitate async

Cargo.toml
Currently users would have to depend manually on `curve25519-dalek` to enable Serde.
This seems to have been lost back in https://github.com/facebook/opaque-ke/pull/250, I suspect because enabling crate features on optional dependencies with `?` wasn't available back then.
=> Enable `curve25519-dalek/serde`

src/keypair.rs, src/lib.rs, src/messages.rs, src/opaque.rs, src/tests/remote_key.rs
This PR expands the API to enable storing the OPRF seed on an HSM. The operation that is externalized here is the HDKF expand operation in `CreateRegistrationResponse` and `CreateCredentialResponse`, which is used to derive the per-user OPRF key. The API and documentation call the output of the HKDF operation "key material".
The change is rather small and the API flow only changes minimally. Instead of calling `ServerRegistration::start()`, users have to call `ServerSetup::key_material_info()` first, generate the key material and then call `ServerRegistration::start_with_key_material()`. The same with `ServerLogin::builder()`, users generate the key material and then call `ServerLogin::builder_with_key_material()`.
Notably the current API does not allow to have a remote OPRF seed but a …
=> Remote OPRF Seed Support

Cargo.toml, src/key_exchange/group/curve25519.rs, src/key_exchange/group/ed25519.rs, src/key_exchange/group/elliptic_curve.rs, src/key_exchange/group/ristretto255.rs, src/key_exchange/shared.rs, src/key_exchange/sigma_i/ecdsa.rs, src/key_exchange/sigma_i/mod.rs, src/key_exchange/tripledh.rs, src/keypair.rs, src/messages.rs, src/opaque.rs
Until now we had a manual Serde De/Serialization implementation for `Public/PrivateKey`. This PR changes that to shift the responsibility on the `Group` implementation. Now `Group` implementations can choose their own way to format their keys.
As `elliptic-curve` is the only implementation with dedicated types for non-identity elements and non-zero scalars, all other ones now require custom Serde implementations.
Resolves #300.
Based on #378.
=> Move Serde De/Serialization to `Group` Implementation
